### ISSUE TITLE
About this project

### ISSUE THREAD

**Issue by Lygggggg** [shashacks/IRL_Transition#1]
hello,i am very interested in your project and i‘m studying it.Is there any article that can help me understand this project?

**Comment by Lygggggg** [comment]
other question,  I want to migrate this method of yours to my environment, I don't know if it is feasible.

**Comment by shashacks** [comment]
hello,i am very interested in your project and i‘m studying it.Is there any article that can help me understand this project?
**=>** This project is under review, so I didn't upload the final version of it. But you can get the code here (https://openreview.net/forum?id=6vkzF28Hur8) You can also check the paper as well. 

other question, I want to migrate this method of yours to my environment, I don't know if it is feasible.
**=>** Yes of course it's possible if your environments have the adequate functions.

**Comment by Lygggggg** [comment]
> hello,i am very interested in your project and i‘m studying it.Is there any article that can help me understand this project? **=>** This project is under review, so I didn't upload the final version of it. But you can get the code here (https://openreview.net/forum?id=6vkzF28Hur8) You can also check the paper as well.
> 
> other question, I want to migrate this method of yours to my environment, I don't know if it is feasible. **=>** Yes of course it's possible if your environments have the adequate functions.

Okey, thanks!
